name: External event

on: repository_dispatch

jobs:
  hello-world:
    name: hello world
    runs-on: ubuntu-latest
    steps:
      - name: echo it
        run: echo "$EVENT_TYPE"
        if: github.event.action == "cloudsmith_event"
        env:
          EVENT_TYPE: ${{ github.event.action }}
