name: Foo

on:
  workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "update-documentation"
  cancel-in-progress: true

jobs:
  generate-documentation:
    name: Generate documentation for release
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/library-documentation-action-v2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate documentation
        run: /entrypoint.py
        env:
          INPUT_SITE_URL: "https://ponylang.github.io/action-testing/"
          INPUT_LIBRARY_NAME: "http"
          INPUT_DOCS_BUILD_DIR: "build/http-docs"

