on: push

jobs:
  changelog-bot:
    runs-on: ubuntu-latest
    name: Update CHANGELOG.md
    steps:
      - uses: actions/checkout@v1
      - name: Update Changelog if applicable
        uses: ponylang/changelog-bot-action@5-and-6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
