name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-entrypoint-py:
    name: Lint entrypoint.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: pylint
        run: make pylint

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Verify CHANGELOG
        run: changelog-tool verify
