name: PR

on: pull_request

jobs:
  lint-entrypoint-py:
    name: Lint entrypoint.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pylint
        run: make pylint

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v2
      - name: Verify CHANGELOG
        run: changelog-tool verify
