name: PR

on: pull_request

jobs:
  lint-entrypoint-py:
    name: Lint entrypoint.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pylint
        run: make pylint

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  error-message:
    name: This will result in an error message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Error time!
        run: bash foo/error-out.bash
