name: PR

on: pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint GitHub Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check workflow files
        uses: docker://ponylang/shared-docker-ci-actionlint:20230810
        with:
          args: -color

  lint-entrypoint-py:
    name: Lint entrypoint.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pylint
        run: make pylint

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v2
      - name: Verify CHANGELOG
        run: changelog-tool verify
