name: Release Notes Reminder Bot

on:
  pull_request_target:
    types: [labeled]

jobs:
  release-note-reminder-bot:
    runs-on: ubuntu-latest
    name: Prompt for release notes
    steps:
      - name: Prompt for release notes
        uses: ponylang/release-notes-reminder-bot-action@forked-repos
        env:
           API_CREDENTIALS: ${{ secrets.PONYLANG_MAIN_API_TOKEN}}
