name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-release:20191107
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: ponylang/release-bot-action@master
        with:
          step: trigger-release-announcement
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
