name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  build-library-documentation:
    runs-on: ubuntu-latest
    name: Build library documentation
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: docker://ponylang/library-documentation-action:0.1.6
        with:
          library_name: "http"
          site_url: "https://ponylang.github.io/action-testing/"
          docs_build_dir: "build/http-docs"
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs:
      - build-library-documentation

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Trigger
        uses: ponylang/release-bot-action@action-yml-version
        with:
          entrypoint: trigger-release-announcement.bash
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
