name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  update-version-in-readme-examples:
    runs-on: ubuntu-latest
    name: Update version in README examples
    steps:
      - name: Update version in README examples
        uses: ponylang/action-readme-version-updater@master
        with:
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          API_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}

  build-library-documentation:
    runs-on: ubuntu-latest
    name: Build library documentation
    steps:
      - name: Build
        uses: ponylang/library-documentation-action@initial
        with:
          library_name: "appdirs"
          docs_build_dir: "build/appdirs-docs"
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs: [update-version-in-readme-examples]
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: ponylang/release-bot-action@default-branch-override
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
          default_branch: "master"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
