name: Release Notes Reminder Bot

on:
  pull_request:
    types: [labeled]

jobs:
  release-note-reminder-bot:
    runs-on: ubuntu-latest
    name: Prompt for release notes
    steps:
      - name: Prompt for release notes
        uses: ponylang/release-notes-reminder-bot-action@master
        env:
           API_CREDENTIALS: ${{ secrets.RELEASE_TOKEN }}
