name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  # Artifact building steps go here

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: ponylang/release-bot-action@0.2.0
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
