name: Send failure to zulip

on:
  workflow_dispatch

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Generate documentation and upload
        run: exit 1
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip@v0.1.2
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: 'notifications'
          type: 'stream'
          topic: 'Scheduled job failure'
          content: |
            A scheduled job for ${{ env.GITHUB_REPOSITORY }} failed.

            See ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY}}/actions/runs/${{ env.GITHUB_RUN_ID}} for more information.
