name: Start a release

on:
  push:
    tags: release-\d+.\d+.\d+

jobs:
  start-a-release:
    name: Start a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Start
        uses: ponylang/release-bot-action@checkout-v2
        with:
          entrypoint: start-a-release.bash
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
