name: Start a release

on:
  push:
    tags: release-*.*.*

jobs:
  start-a-release:
    name: Start a release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-release:20191107
    steps:
      - uses: actions/checkout@v1
      - name: Start
        uses: ponylang/release-bot-action@master
        with:
          step: start-a-release
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
