name: Sync discussion

on:
  issues:
    types:
      - opened
      - reopened
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  add-sync-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add sync label
        uses: andymckay/labeler@467347716a3bdbca7f277cb6cd5fa9c5205c5412
        with:
          add-labels: "discuss at sync"
